name: Issue report
description: Report something that's missing, that you have trouble with or that stopped working
labels: [issue-report]

body:
  - type: input
    id: channel
    attributes:
        label: Channel name\id

  - type: input
    id: user
    attributes:
        label: User name\id

  - type: textarea
    id: description
    validations:
        required: true
    attributes:
        label: Describe your issue
        description: |
            Write a brief description of your issue.

  - type: input
    id: versions
    validations:
        required: true
    attributes:
        label: Browser version
