import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import MainLayout from "../layouts/Layout";
import ppSlide from "../assets/images/ppSlide.gif";
import type { ReactElement } from "react";

export default function Custom500() {
  return (
    <div>
      <Head>
        <title>Logs | 500</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pt-16 pb-12 flex flex-col h-[90vh]">
        <main className="flex-grow flex flex-col justify-center max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex-shrink-0 inline-flex justify-center">
            <Image className="h-12 w-auto" src={ppSlide} alt="pp slide" />
          </div>
          <div className="py-8">
            <div className="text-center">
              <p className="text-sm font-semibold text-primary uppercase tracking-wide">
                500 error
              </p>
              <h1 className="mt-2 text-4xl font-extrabold text-gray-900 dark:text-gray-100 tracking-tight sm:text-5xl">
                Internal Server Error.
              </h1>
              <p className="mt-2 text-base text-gray-500 dark:text-gray-200">
                Yes, this is a 500 error. How could you tell?
              </p>
              <div className="mt-6">
                <Link href="/" passHref>
                  <span className="text-base font-medium text-primary hover:text-primaryLight transition duration-200 cursor-pointer">
                    Go back home
                  </span>
                </Link>
              </div>
            </div>
          </div>
        </main>
        <footer className="flex-shrink-0 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8">
          <nav className="flex justify-center space-x-4">
            <a
              href="https://github.com/ttvLogs/logs-next/issues"
              target="_blank"
              rel="noreferrer"
            >
              <span className="text-sm font-medium text-gray-500 hover:text-gray-600">
                Issues
              </span>
            </a>
          </nav>
        </footer>
      </div>
    </div>
  );
}

Custom500.getLayout = (page: ReactElement) => <MainLayout>{page}</MainLayout>;
