import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container h-screen flex flex-col text-5xl">
        <div className="my-auto mx-auto text-center space-y-2">
          <h1>
            Welcome to{" "}
            <a href="https://nextjs.org" className="text-blue-500 font-medium hover:text-blue-700 duration-200">
              Next.js!
            </a>
          </h1>
          <h2 className="font-medium">
            Nextjs, Tailwind CSS JIT, Prisma
          </h2>
        </div>
      </main>
    </div>
  );
};

export default Home;
