import Head from "next/head";
import Home from "./index";
import { SlideOver } from "../components";
import MainLayout from "../layouts/Layout";
import type { ReactElement } from "react";

function Settings() {
  return (
    <div>
      <Head>
        <title>Logs | Settings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SlideOver>
        <div className="flex flex-col space-y-3">
          <p>Show timestamp</p>
          <p>Show name</p>
          <div>
            <p>Show emotes</p>
            <div className="ml-4">
              <p>FFZ emotes</p>
              <p>BTTV emotes</p>
              <p>7tv emotes(?)</p>
              <p>Sub emotes(?)</p>
            </div>
          </div>
          <p>Twitch chat mode(?)</p>
          <p>/me lines</p>
          <p>Bots messages</p>
          <p>Sort: (✔️) Newest (❌) Oldest</p>
        </div>
      </SlideOver>
    </div>
  );
}
export default Settings;

Settings.getLayout = (page: ReactElement) => (
  <MainLayout>
    <Home/>
    {page}
  </MainLayout>
);

